version: '3.8'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    depends_on:
      - nginx

  nginx:
    build: ./requirements/nginx
    ports: 
    - "80:80"

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    networks:
      - inception