version: '3.8'

networks:
  inception:
    name: inception
    driver: bridge


services:
  nginx:
    container_name: nginx
    networks: 
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requeriments/nginx
    env_file: ./.env
    ports:
      - "443:443"
    restart: on-failure
    volumes: 
      - "wordpress:/var/www/wordpress"

  mariadb:
    container_name: mariadb
    hostname: mariadb.srcs_inception
    networks:
      - inception
    build: 
      context: ./requeriments/mariadb
    env_file: ./.env
    restart: unless-stopped
    expose:
      - "3306"
    volumes: 
      - "mariadb:/var/lib/mysql"

  wordpress:
    container_name: wordpress
    hostname: wordpress.srcs_inception
    networks:
      - inception
    build: 
      context: ./requeriments/wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "wordpress:/var/www/wordpress"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/sergio/data/mariadb/"
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sergio/data/wordpress/